### ISSUE TITLE
Release 0.4.3

### ISSUE THREAD

**Issue by Juanlu001** [Turbo87/utm#33]

**Comment by SteveAlexander** [comment]
Hi! I hope this is not an inappropriate place to write this...

The utm package is awesome — simplified a lot of things for me. Thanks!

I'm currently installing it into `pip` from the git repo, because 4.2 doesn't have the `force_zone_letter` argument in `utm.from_latlon`, and I'm using that.

Also, I see that the pull request https://github.com/Turbo87/utm/pull/35 fixes a bug when a using forced zones near the equator.

I wonder if you'd have time to do a `0.4.3` release including the above, in the near future? If there's anything I could help with regarding documentation or testing, I'd be glad to assist.

**Comment by Turbo87** [comment]
sorry, that this slipped through for so long. I've just released v0.5.0 to PyPI.
